version: "3.7"
services:
  database:
    image: mysql:5.7
    volumes:
      - ./mysql/db/entrypoint:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=feedback"
      - "MYSQL_ROOT_PASSWORD=geheim"
  web:
    image: gradle:jdk13
    command: gradle bootRun
    volumes:
      - .:/home/gradle
    ports:
      - "8080:8080"
